config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root to: 'home#index'
  get 'home/show'

  get '/home/detail/:id', to: 'home#detail', as: 'detail'

  

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/scheduled_work.rb
class ScheduledWork < ApplicationRecord
end

app/models/scrapper_result.rb
class ScrapperResult < ApplicationRecord
    # t.integer "site_captures_id"
    # t.integer "scheduled_works_id"
    # t.string "brand"
    # t.text "name"
    # t.text "url"
    # t.string "price"
    # t.string "sale"
    # t.datetime "created_at", precision: 6, null: false
    # t.datetime "updated_at", precision: 6, null: false
    # t.string "sku"

    


    def self.fetch(options = {})
        collection = super(options)
        collection = attribute_filter(collection, "created_at", options)
        collection = attribute_filter(collection, "name", options)
        collection = attribute_filter(collection, "sku", options)
        collection = collection.where("created_at >= ? between created_at <= ?", created_at, created_at)
        #collection = blocked_unblocked_filter(collection, options)
        #collection = document_query(collection, options)
        collection
    end
end

app/models/site_capture.rb
class SiteCapture < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_admin!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "application_home"
  def index
    
    documents = ScrapperResult.last(50).reverse #lista home
    @list = ScrapperResult.last(5).reverse #lista home
    @productos = ScrapperResult.select(:brand, :name)
  end

  def detail
    filter = ScrapperResult.where(id:params[:id])
    @product = ScrapperResult.where(name:filter.first[:name], site_captures_id: filter.first[:site_captures_id])
    @list = @product
  end

  def show
    fdate = "#{params[:fdate]} 00:00:01"
    ldate = "#{params[:ldate]} 23:59:59"
    documents = ScrapperResult.all
    documents = documents.where("created_at between ?  and ?", fdate, ldate)
    documents = documents.where("name ilike '%#{params[:brand]}%'" )
    @list = documents.paginate(page: params[:page], per_page: 8) #lista buscar
  end

  private
    def person_params
      params.require(:scrapper_results).permit(:fdate, :ldate, :business, :brand)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def format_number(number)
        num_groups = number.to_s.chars.to_a.reverse.each_slice(3)
        num_groups.map(&:join).join(',').reverse
      end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/home/_list.html.erb
<table id="datatable" class="table table-borderless table-thead-bordered table-nowrap table-align-middle card-table dataTable no-footer" role="grid" aria-describedby="datatable_info">
    <thead class="thead-light">
        <tr role="row">
            <th aria-label="Full name">Brand</th>
            <th aria-label="Name">Description</th>
            <th aria-label="price">Price</th>
            <th aria-label="Code company">Code</th>
            <th aria-label="Date capture">Date time</th>
        </tr>
    </thead>
    <tbody>
        
        <% @list.each do |product| %>
        <tr role="row" class="odd">
            <td class="table-column-ps-0"><%= product[:brand] %></td>
            <td><%= product[:name] %></td>
            <td>$ <%= product[:price] %></td>
            <td>
                <a href='<%= product[:url] %>'>
                    <%= product[:sku] %>
                </a>
            </td>
            <td><%= product[:created_at] %></td>
            <td>
                <div class="input-group mb-3">
                    <%= button_to "See more", detail_path(product[:id]), :id => "open-contacts-dialog-btn", :class => "btn btn-primary btn-sm", :method => :get %>
                </div>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/home/detail.html.erb
<div class="container mt-4 border">
    <div class="container-content">
        <div class="row">
            <div class="col-12">
                <div class="row">
                    <div class="col-xs-6">
                        <h3>Historical product</h3>
                        <%= column_chart @product.pluck(:created_at, :price)%>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="row">
                    <div class="col-xs-6">
                        <h3>Historical product</h3>
                        <%= render 'list' %>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
    

app/views/home/index.html.erb
<div class="row">
    <div class="col-12">
        <div class="card mb-3 mb-lg-5">
            <!-- Header -->
            <div class="card-header">
                <div class="row justify-content-between align-items-center flex-grow-1">
                    <div class="col-md">
                        <div class="d-flex justify-content-between align-items-center">
                            <h4 class="card-header-title">Last <b><%=@list.count%></b> charges</h4>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Table -->
            <div class="table-responsive datatable-custom">
                    <%= render 'list' %>
                <div class="dataTables_info" id="datatable_info" role="status" aria-live="polite"></div>
            </div>
            <!-- End Table -->
            <!-- Footer -->
            <div class="card-footer">
            
            </div>
            <!-- End Footer -->
        </div>
    </div>
    <div class="col-12 col-sm-12">
        <div class="card mb-2 col-sm-12 mb-lg-4">
            
            <!-- Header -->
            <div class="card-header">
                <div class="row justify-content-between align-items-center flex-grow-1">
                    <div class="col-md">
                        <div class="d-flex justify-content-between align-items-center">
                            <h4 class="card-header-title">Filter list</h4>
                        </div>
                    </div>
                </div>
            </div>
            
            <%= form_with url: home_show_url, method: :get do |form| %>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12 col-md-6">
                            <div class="input-group input-group-default mb-1">
                                <span class="input-group-text" id="inputGroup-sizing-default">First date</span>
                                <input type="text" name="fdate" id="fdate" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" required="required">
                            </div>
                        </div>
                        <div class="col-12 col-md-6">
                            <div class="input-group input-group-default mb-1">
                                <span class="input-group-text" id="inputGroup-sizing-default">Last date</span>
                                <input type="text" name="ldate" id="ldate" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" required="required">
                            </div>

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 col-md-6">
                            <div class="input-group input-group-default mb-1">
                                <span class="input-group-text" id="inputGroup-sizing-default">Text</span>
                                <input type="text" name="brand" id="brand" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3 col-md-3 ">
                            <div class="input-group mb-3">
                                <button type="submit" class="btn btn-primary">Search</button>
                            </div>
                        </div>
                        <div class="col-3 col-md-3">
                            <div class="input-group mb-3">
                                <button type="button" class="btn btn-primary">Export</button>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/home/show.html.erb
<div class="container mt-4 border">
  <div class="container-content">
    <div class="row">
        <div class="col-12">
            <div class="card mb-3 mb-lg-5">
                <!-- Header -->
                <div class="card-header">
                    <div class="row justify-content-between align-items-center flex-grow-1">
                        <div class="col-md">
                            <div class="d-flex justify-content-between align-items-center">
                                <h4 class="card-header-title">Result filter: <b><%=@list.count%></b></h4>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Table -->
                <div class="table-responsive datatable-custom">
                       <%= render 'list' %>
                    <div class="dataTables_info" id="datatable_info" role="status" aria-live="polite"></div>
                </div>
                <!-- End Table -->
                <!-- Footer -->
                <div class="card-footer">
                    <div class="apple_pagination">
                        <div class="page_info">
                            <%= page_entries_info @list %>
                        </div>
                        <%= will_paginate @list, :container => false %>
                    </div>

                </div>
                <!-- End Footer -->
            </div>
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dashboard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application_home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dashboard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container mt-4">
      <div class="container-content">
        <%= render 'shared/navbar'%>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%=root_path%>">
      <img src="<%= asset_path  "logo-cartouches_325x.avif" %>" alt="" width="150" height="50">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%=root_path%>">Home</a>
        </li>

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Create user</a>
        </li>
        <li class="nav-item">
          
          <%= link_to "Sign Out", destroy_admin_session_path, method: :delete, class:"nav-link active" %>
        </li>
      </ul>
    </div>
  </div>
</nav>